In [2]:
import numpy as np

In [3]:
my_list=[1,2,3,4]

In [4]:
np.array(my_list)

array([1, 2, 3, 4])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr1=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,0],[12,13,14,15]]])
arr1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11,  0],
        [12, 13, 14, 15]]])

In [22]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


In [23]:
np.zeros(3)

array([0., 0., 0.])

In [27]:
np.zeros((5,5,5,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0.,

In [65]:
arr=np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2,4:5])

[[ 5]
 [10]]


In [74]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [100]:
arr=np.array([1,2,3,0])

In [101]:
arr.astype(bool)

array([ True,  True,  True, False])

In [105]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [106]:
arr=np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr.shape

(2, 5)

In [136]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,13,14,15,16])


In [137]:
newarr=arr.reshape(2,2,2,2)

In [138]:
newarr

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [147]:
newarr[0,0,1,0]

3

In [152]:
newarr[0:2,0:1]

array([[[[ 1,  2],
         [ 3,  4]]],


       [[[ 9, 10],
         [11, 12]]]])

In [153]:
for x in newarr:
    print(x)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]


In [154]:
for x in arr:
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [155]:
arr=np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [159]:
for x in arr:
    for y in x:
        z=y+y
        print(z)

2
4
6
8
10
12
14
16
18
20


In [195]:
import numpy as np

arr1 = np.array([[[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20],[21, 22, 23, 24]]])

arr2 = np.array([[[25, 26, 27, 28], [29, 30, 31, 32],[33, 34, 35, 36]],[[37, 38, 39, 40], [41, 42, 43, 48],[49, 50, 51, 52]]])
arr3 = np.array([[[53, 54, 55, 56], [57, 58, 59, 60],[61, 62, 63, 64]],[[65, 66, 67, 68], [69, 70, 71, 72],[73, 74, 75, 76]]])
for x in np.nditer(arr[:,0::2]):
  print(x)
print("--------")
for idx, x in np.ndenumerate(arr):
  print(idx, x)
print("--------")
arr=np.vstack((arr1,arr2,arr3))

print(arr)

print("--------")
for idx, x in np.ndenumerate(arr):
  print(idx, x)
print("--------")


1
2
3
4
9
10
11
12
13
14
15
16
21
22
23
24
25
26
27
28
33
34
35
36
37
38
39
40
49
50
51
52
53
54
55
56
61
62
63
64
65
66
67
68
73
74
75
76
--------
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(0, 1, 3) 8
(0, 2, 0) 9
(0, 2, 1) 10
(0, 2, 2) 11
(0, 2, 3) 12
(1, 0, 0) 13
(1, 0, 1) 14
(1, 0, 2) 15
(1, 0, 3) 16
(1, 1, 0) 17
(1, 1, 1) 18
(1, 1, 2) 19
(1, 1, 3) 20
(1, 2, 0) 21
(1, 2, 1) 22
(1, 2, 2) 23
(1, 2, 3) 24
(2, 0, 0) 25
(2, 0, 1) 26
(2, 0, 2) 27
(2, 0, 3) 28
(2, 1, 0) 29
(2, 1, 1) 30
(2, 1, 2) 31
(2, 1, 3) 32
(2, 2, 0) 33
(2, 2, 1) 34
(2, 2, 2) 35
(2, 2, 3) 36
(3, 0, 0) 37
(3, 0, 1) 38
(3, 0, 2) 39
(3, 0, 3) 40
(3, 1, 0) 41
(3, 1, 1) 42
(3, 1, 2) 43
(3, 1, 3) 48
(3, 2, 0) 49
(3, 2, 1) 50
(3, 2, 2) 51
(3, 2, 3) 52
(4, 0, 0) 53
(4, 0, 1) 54
(4, 0, 2) 55
(4, 0, 3) 56
(4, 1, 0) 57
(4, 1, 1) 58
(4, 1, 2) 59
(4, 1, 3) 60
(4, 2, 0) 61
(4, 2, 1) 62
(4, 2, 2) 63
(4, 2, 3) 64
(5, 0, 0) 65
(5, 0, 1) 66
(5, 0, 2) 67
(5, 0, 3) 68
(5, 1, 0) 69
(5, 1, 1) 70
(5,

In [199]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3, axis=1)
find=np.where(arr%2==0)

print(find)

(array([0, 1, 2, 3, 4, 5], dtype=int64), array([1, 1, 1, 1, 1, 1], dtype=int64))


In [200]:
arr2d = np.zeros((10,10))

In [201]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [202]:
arr_length = arr2d.shape[1]

In [203]:
arr_length

10

In [204]:
arr2d.shape[1]

10

In [205]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [206]:
arr=np.arange(0,10)

In [207]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [208]:
arr*10*arr

array([  0,  10,  40,  90, 160, 250, 360, 490, 640, 810])

In [209]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])